/* Regression: parsing many anonymous nested struct field types must not keep
 * a stale StructDef* for the containing struct across structs[] growth. */
struct outer {
    struct { int v; } f0;
    struct { int v; } f1;
    struct { int v; } f2;
    struct { int v; } f3;
    struct { int v; } f4;
    struct { int v; } f5;
    struct { int v; } f6;
    struct { int v; } f7;
    struct { int v; } f8;
    struct { int v; } f9;
    struct { int v; } f10;
    struct { int v; } f11;
    struct { int v; } f12;
    struct { int v; } f13;
    struct { int v; } f14;
    struct { int v; } f15;
    struct { int v; } f16;
    struct { int v; } f17;
    struct { int v; } f18;
    struct { int v; } f19;
    struct { int v; } f20;
    struct { int v; } f21;
    struct { int v; } f22;
    struct { int v; } f23;
    struct { int v; } f24;
    struct { int v; } f25;
    struct { int v; } f26;
    struct { int v; } f27;
    struct { int v; } f28;
    struct { int v; } f29;
    struct { int v; } f30;
    struct { int v; } f31;
    struct { int v; } f32;
    struct { int v; } f33;
    struct { int v; } f34;
    struct { int v; } f35;
    struct { int v; } f36;
    struct { int v; } f37;
    struct { int v; } f38;
    struct { int v; } f39;
    struct { int v; } f40;
    struct { int v; } f41;
    struct { int v; } f42;
    struct { int v; } f43;
    struct { int v; } f44;
    struct { int v; } f45;
    struct { int v; } f46;
    struct { int v; } f47;
    struct { int v; } f48;
    struct { int v; } f49;
    struct { int v; } f50;
    struct { int v; } f51;
    struct { int v; } f52;
    struct { int v; } f53;
    struct { int v; } f54;
    struct { int v; } f55;
    struct { int v; } f56;
    struct { int v; } f57;
    struct { int v; } f58;
    struct { int v; } f59;
    struct { int v; } f60;
    struct { int v; } f61;
    struct { int v; } f62;
    struct { int v; } f63;
    struct { int v; } f64;
    struct { int v; } f65;
    struct { int v; } f66;
    struct { int v; } f67;
    struct { int v; } f68;
    struct { int v; } f69;
    struct { int v; } f70;
    struct { int v; } f71;
    struct { int v; } f72;
    struct { int v; } f73;
    struct { int v; } f74;
    struct { int v; } f75;
    struct { int v; } f76;
    struct { int v; } f77;
    struct { int v; } f78;
    struct { int v; } f79;
    int tail;
};

int main(void) {
    struct outer o;
    o.f0.v = 10;
    o.f63.v = 20;
    o.f79.v = 12;
    o.tail = 0;
    return o.f0.v + o.f63.v + o.f79.v + o.tail;
}
